### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by reconbot** [EmergingTechnologyAdvisors/node-serialport#746]
I'd like to use this issue to discuss breaking changes to the SerialPort library. `2.0.7` has changed a lot of the internals but left the api largely intact. I'd like to make some goals and address specific api changes.
## Internals and APi Changes
- [x] Cleanup flow control flags #819
- [x] Throw errors during construction instead of doing them in a zalgo infested callback #820
- [x] Stop removing registered event handlers ever #764
- [x] Move the openImmediately argument to options #809, 
- [x] Explore a [Streams interface](https://github.com/nodejs/readable-stream) either as a primary or additional interface #832 
- [x] Cleanup the bindings layer #738 
- [ ] Support `chrome.serialport` #739
- [x] Fix the disconnect behavior #702 
- [ ] Explore the [whatwg serial api](http://whatwg.github.io/serial/)
- [ ] Reconnect options
- [x] Reading RTS and CTS or having events #291 
- Your hopes and dreams here

**Comment by reconbot** [comment]
My current plans involve a 3.0 release that removes the close and disconnect `removeAllListeners()` calls. These are basically bugs imho, but they are major api changes so 3.0.0

A 4.0 release will take a bit longer and need some discussion. I want to clean up options, and construor apis (eg throw immediatly on config issues, ensure update does the right thing everywhere. And lastly kill the factory. This will also make it a lot easier to have a single disconnect path for windows and everyone else, and isolate the pause/resume functions to the bindings.

**Comment by reconbot** [comment]
I put together a shortlist for [4.0](https://github.com/EmergingTechnologyAdvisors/node-serialport/milestones/4.0)

**Comment by reconbot** [comment]
I have a few links to serialport like interfaces that could be potential bindings layers.

 - https://github.com/garrows/browser-serialport (chrome apps)
 - Monteslu's collection of serialport like objects https://github.com/search?utf8=%E2%9C%93&q=user%3Amonteslu+-serial&type=Repositories&ref=searchresults

**Comment by reconbot** [comment]
Most of these are completed. Gonna close as 5.0 is close to release.
